SizedBox(width: 200,),
Icon(Icons.crop_rotate),
SizedBox(width: 15,),
Icon(Icons.emoji_emotions_outlined),
SizedBox(width: 15,),
Icon(Icons.title),
SizedBox(width: 15,),
Icon(Icons.edit_outlined),

SizedBox(height: MediaQuery.of(context).size.height/1.5,),
Icon(Icons.keyboard_arrow_up_outlined),
Text('Filters'),
SizedBox(height: 10,),
Container(height: 40,width:380,
decoration: BoxDecoration(borderRadius: BorderRadius.all(Radius.circular(30)),color: Colors.grey.shade800),
child:
TextFormField(
controller: area,
textAlignVertical: TextAlignVertical.center,
decoration: InputDecoration(hintText: 'Add a caption...',hintStyle: TextStyle(color: Colors.white,),
border: InputBorder.none,
prefixIcon:IconButton(onPressed:(){},icon:Icon(Icons.add_photo_alternate,color: Colors.white,),),
suffixIcon: IconButton(onPressed: (){},icon: Icon(Icons.av_timer,color: Colors.white,),)),
),
),
SizedBox(height: 20,),

Container(height: 30,width: 60,padding: EdgeInsets.all(5),
decoration: BoxDecoration(borderRadius: BorderRadius.all(Radius.circular(20)),color: Colors.grey.shade800,),
child: Text('Tushar',style: TextStyle(color: Colors.white),),),
SizedBox(width: 270,),
CircleAvatar(child:Icon(Icons.send,color: Colors.white,),backgroundColor: Colors.green,radius: 25,)
